### ISSUE TITLE
Run Multiple Threads Concurrently in Java

### ISSUE THREAD

**Issue by Murgio** [Murgio/Genetic-Algorithm-Montage#1]
If **you** want to contribute here are some useful **notes**:

An implementation of multiple threads would be very useful to calculate the _Fitness Score_ faster than with one worker process. The _Fitness Score_ is crucial and thus a reduction of the time needed to calculate the fitness would tremendously reduce the time per generation.

The **calculateFitness** function is called in the **Population class**:

`for(List<Integer> list : DNAList) { fitnessList.add(fitness.calculateFitness(list)); }`

**Comment by rrishabhj** [comment]
hey, i want to contribute, it is still not clear what you want to do, please elaborate!

**Comment by Murgio** [comment]
@rrishabhj Thank you very much for your support. In the meantime, I already implemented this couple of hours ago so I'm going to close this issue now.

**Happy Hacktoberfest!**
